site_name: change-management-database
site_url: https://indigo-dc.github.io/change-management-database/
site_author: Savarese Giovanni
site_description: Documentation for change-management-database python web service
repo_name: indigo-dc/change-management-database
repo_url: https://github.com/indigo-dc/change-management-database

theme:
  language: en
  name: material
  features:
    - navigation.footer
    - navigation.tabs
    - content.code.copy
    - content.code.select
    - content.code.annotate

#extra:
#  version:
#    provider: mike
#    default: stable

plugins:
  - search
  - social
  - git-authors
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: True
            members_order: source

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: "index.md"
  - Installation: "installation.md"
  - Getting Started: "getting_started.md"
  - Developers: "developers.md"
