version: "3"

services:
  db:
    image: neo4j:5.15
    volumes:
      - dev-db-data:/data
      - dev-db-logs:/logs
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc"]

  oidc-agent:
    image: opensciencegrid/oidc-agent:3.6-release-20230802-1615
    platform: linux/amd64

  base:
    build:
      context: ../.
      target: development
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    depends_on:
      - db
    volumes:
      - ..:/workspace:cached
    environment:
      - NEO4J_SERVER=db
    # Infinite loop to keep container live doing nothing
    command: bash -c "while true; do sleep 1; done"

volumes:
  dev-db-data:
  dev-db-logs:
