trusted_idps:
  - issuer: https://iam.cloud.infn.it/
    group_claim: groups
    user_groups:
      - name: test
        slas:
          - doc_uuid: edfda059a23c439f8ffc06edd484e1a0
            start_date: 2023-09-10
            end_date: 2024-09-25
          - doc_uuid: c2bb880f0aa443a49abcbbbe2e96b48b
            start_date: 2023-10-11
            end_date: 2023-10-25

openstack:
  - name: cloud-cnaf
    status: active
    is_public: false
    support_emails:
      - giovanni.savarese@ba.infn.it
    image_tags: [infn-cloud]
    network_tags: [infn-cloud]
    block_storage_vol_types:
      gold: my type1
      silver: muy-type2
    regions:
      - name: tier1
        location:
          site: INFN CNAF
          country: Italy
      - name: sdds
        location:
          site: INFN Bari
          country: Italy
    auth_url: https://cloud-api-pub.cr.cnaf.infn.it:5000/v3
    identity_providers:
      - endpoint: https://iam.cloud.infn.it/
        name: infn-cc
        protocol: openid
    projects:
      - id: 12bb88070aa443a494bcbbbe2e96b48b
        sla: c2bb880f0aa443a49abcbbbe2e96b48b
        default_public_net: pluto
        default_private_net: pippo
        private_net_proxy:
          ip: 10.1.21.3
          user: topolino
        per_user_limits:
          compute:
            cores: 2
            ram: 2
            public_ips: 2
          block_storage:
            gigabytes: 2
        per_region_props:
          - region_name: sdds
            default_public_net: pluto
            default_private_net: pippo
            private_net_proxy:
              ip: 0.21.1.1
              user: topolino
            per_user_limits:
              compute:
                cores: 2
                ram: 2
                public_ips: 2
              block_storage:
                gigabytes: 2
          - region_name: tier1
            default_public_net: john
            default_private_net: dave
            private_net_proxy:
              ip: 0.21.1.1
              user: jenny
            per_user_limits:
              compute:
                cores: 3
                ram: 2
                public_ips: 4
              block_storage:
                gigabytes: 2
