trusted_idps:
  - issuer: https://iam.cloud.infn.it/
    group_claim: groups
    user_groups:
      - name: test
        slas:
          - doc_uuid: edfda059a23c439f8ffc06edd484e1a0
            start_date: 2023-09-10
            end_date: 2024-09-25
      - name: prova
        slas:
          - doc_uuid: cdfda059a23c439f8ffc06edd484e1a0
            start_date: 2023-09-11
            end_date: 2023-10-25
      - name: pippo
        slas:
          - doc_uuid: bdfda059a23c439f8ffc06edd484e1a0
            start_date: 2024-09-10
            end_date: 2026-10-25

openstack:
  - name: recas-ba
    status: active
    is_public: false
    support_emails: [giovanni.savarese@ba.infn.it, marica.antonacci@ba.infn.it]
    regions:
      - name: RegionOne
        location:
          site: INFN Bari
          country: Italy
    auth_url: https://keystone.recas.ba.infn.it:443
    identity_providers:
      - name: infn-cloud
        protocol: openid
        endpoint: https://iam.cloud.infn.it/
    projects:
      - id: a8b324a0f4f349d28e98e4e78b11bacc
        sla: edfda059a23c439f8ffc06edd484e1a0
      - id: edfda059a23c439f8ffc06edd484efa0
        sla: bdfda059a23c439f8ffc06edd484e1a0
      - id: 83be7870dbb54d4a988f89ea77e9e2b9
        sla: cdfda059a23c439f8ffc06edd484e1a0
